# set the correct runtime
runtime: ruby21

test: |
  if [[ ! -n "${ROCK_ARG1}" ]]  || [[ ! -n "${ROCK_ARG2}" ]]; then
    die "Usage: rock test SITE TAG"
  fi


  LANGUAGE="${ROCK_ARG2}" SITE="${ROCK_ARG1}" exec rspec --tag "${ROCK_ARG2}"